import { Inter } from "next/font/google";
import "./sublimation.css"
import Header from "../assessment/header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Computer assessment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header/>
      
      <body className={inter.className}>{children}</body>
    </html>
  );
}
